services:
  app:
    container_name: irl_dir
    image: irl_dir
    deploy:
      resources:
        limits:
          cpus: '30.0'
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        USERNAME: ${USERNAME}
    volumes:
      - ./:/app/
    stdin_open: true
    tty: true