"""
全活動イベント抽出スクリプト

data/raw_json/openstack__*.json から、各 reviewer の全活動イベントを抽出。

イベント種別:
  request    : レビュー依頼を受けた（combined_raw.csv から流用、label=accept/reject）
  vote       : Code-Review +1/+2/-1/-2 を投票
  comment    : 非自動生成のコメントを投稿（ボット除外）
  authored   : 自分が change の owner として作成
  patchset   : 自分の change に新しい patch set を upload

出力 CSV: data/combined_events.csv
列: email, project, change_id, event_type, timestamp, dirs (json),
    vote_value (int|null), label (int|null, request 行のみ)

使い方:
    uv run python scripts/build_activity_events.py \
        --raw-json data/raw_json/openstack__heat.json \
        --reviews data/combined_raw.csv \
        --output data/events/heat_events.csv

複数プロジェクトを一括:
    uv run python scripts/build_activity_events.py \
        --raw-json-dir data/raw_json \
        --reviews data/combined_raw.csv \
        --output data/combined_events.csv
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from pathlib import Path
from typing import Dict, FrozenSet, Iterable, List, Optional, Set
from urllib.parse import quote

import pandas as pd

from review_predictor.IRL.features.path_features import file_to_dir, extract_dirs

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")


VOTE_RE = re.compile(r"Code-Review([+-]\d)")
BOT_TAG_USERNAMES = {"zuul", "openstack-zuul", "gerrit", "openstack-ci"}
BOT_EMAIL_SUFFIXES = ("@review.openstack.org",)


def _is_bot(account: dict) -> bool:
    if not account:
        return True
    tags = account.get("tags") or []
    if "SERVICE_USER" in tags:
        return True
    username = (account.get("username") or "").lower()
    if username in BOT_TAG_USERNAMES:
        return True
    email = (account.get("email") or "").lower()
    if any(email.endswith(s) for s in BOT_EMAIL_SUFFIXES):
        return True
    return False


def _change_files(change: dict) -> Set[str]:
    files: Set[str] = set()
    for rev in (change.get("revisions") or {}).values():
        if not isinstance(rev, dict):
            continue
        for fp in (rev.get("files") or {}).keys():
            if fp.startswith("/"):
                continue
            files.add(fp)
    return files


def _change_key(change: dict) -> Optional[str]:
    project = change.get("project")
    number = change.get("_number")
    if project is None or number is None:
        return None
    return f"{quote(project, safe='')}~{number}"


def extract_events_from_change(
    change: dict,
    depth: int = 2,
) -> List[dict]:
    """1 つの change から全活動イベントを抽出する（request 以外）。"""
    out: List[dict] = []

    project = change.get("project")
    if project is None:
        return out
    change_id = _change_key(change)
    if change_id is None:
        return out

    files = _change_files(change)
    dirs = sorted(extract_dirs(files, depth=depth))
    dirs_json = json.dumps(dirs, ensure_ascii=False) if dirs else "[]"

    owner = change.get("owner") or {}
    owner_email = (owner.get("email") or "").lower()
    created = change.get("created")

    # authored event (owner が patch set 1 を作成)
    if owner_email and not _is_bot(owner) and created:
        out.append(
            dict(
                email=owner_email,
                project=project,
                change_id=change_id,
                event_type="authored",
                timestamp=created,
                dirs=dirs_json,
                vote_value=None,
                label=None,
            )
        )

    # messages から vote / comment / patchset を抽出
    for msg in change.get("messages") or []:
        author = msg.get("author") or {}
        email = (author.get("email") or "").lower()
        if not email or _is_bot(author):
            continue
        date = msg.get("date")
        if not date:
            continue
        text = msg.get("message") or ""
        tag = msg.get("tag")

        # patch set upload
        if tag == "autogenerated:gerrit:newPatchSet":
            out.append(
                dict(
                    email=email,
                    project=project,
                    change_id=change_id,
                    event_type="patchset",
                    timestamp=date,
                    dirs=dirs_json,
                    vote_value=None,
                    label=None,
                )
            )
            continue
        if tag and tag.startswith("autogenerated:zuul"):
            # CI ボット系は skip
            continue

        # vote (text に Code-Review[+-]N が含まれる)
        m = VOTE_RE.search(text)
        if m:
            try:
                vote_value = int(m.group(1))
            except ValueError:
                vote_value = None
            out.append(
                dict(
                    email=email,
                    project=project,
                    change_id=change_id,
                    event_type="vote",
                    timestamp=date,
                    dirs=dirs_json,
                    vote_value=vote_value,
                    label=None,
                )
            )
            continue

        # 残ったものはコメント（自動生成 tag 系を除いた人間メッセージ）
        # tag が autogenerated:gerrit:* の merged/abandon/setTopic 等は skip
        if tag and tag.startswith("autogenerated:gerrit:"):
            continue
        out.append(
            dict(
                email=email,
                project=project,
                change_id=change_id,
                event_type="comment",
                timestamp=date,
                dirs=dirs_json,
                vote_value=None,
                label=None,
            )
        )

    return out


def build_change_dirs_map(changes: Iterable[dict], depth: int = 2) -> Dict[str, str]:
    """change_id -> dirs (json string)"""
    out: Dict[str, str] = {}
    for ch in changes:
        ck = _change_key(ch)
        if ck is None:
            continue
        files = _change_files(ch)
        dirs = sorted(extract_dirs(files, depth=depth))
        out[ck] = json.dumps(dirs, ensure_ascii=False) if dirs else "[]"
    return out


def process_project(
    json_path: Path,
    reviews_df: pd.DataFrame,
    depth: int = 2,
) -> pd.DataFrame:
    logger.info(f"loading {json_path.name} ...")
    with open(json_path, "r", encoding="utf-8") as f:
        changes = json.load(f)
    logger.info(f"  {json_path.name}: {len(changes):,} changes")

    # 非 request イベント
    rows: List[dict] = []
    for ch in changes:
        rows.extend(extract_events_from_change(ch, depth=depth))
    logger.info(f"  {json_path.name}: extracted {len(rows):,} non-request events")

    # request イベント (combined_raw.csv から該当プロジェクトのみ)
    proj_field = changes[0].get("project") if changes else None
    if proj_field is None:
        # ファイル名から推定 ("openstack__heat.json" -> "openstack/heat")
        stem = json_path.stem  # openstack__heat
        proj_field = stem.replace("__", "/", 1)
    sub = reviews_df[reviews_df["project"] == proj_field].copy()
    logger.info(
        f"  {json_path.name}: {len(sub):,} request events from combined_raw.csv "
        f"(project={proj_field})"
    )

    # change_id -> dirs map で dirs を埋める
    cd_map = build_change_dirs_map(changes, depth=depth)

    sub["dirs"] = sub["change_id"].map(lambda cid: cd_map.get(cid, "[]"))
    request_rows = []
    for _, r in sub.iterrows():
        request_rows.append(
            dict(
                email=str(r["email"]).lower(),
                project=r["project"],
                change_id=r["change_id"],
                event_type="request",
                timestamp=r["timestamp"],
                dirs=r["dirs"],
                vote_value=None,
                label=int(r["label"]),
            )
        )
    logger.info(f"  {json_path.name}: built {len(request_rows):,} request rows")

    df = pd.DataFrame(rows + request_rows)
    return df


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--raw-json", type=Path, default=None)
    parser.add_argument("--raw-json-dir", type=Path, default=None)
    parser.add_argument("--reviews", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--depth", type=int, default=2)
    args = parser.parse_args()

    if not args.raw_json and not args.raw_json_dir:
        raise SystemExit("either --raw-json or --raw-json-dir is required")

    json_paths: List[Path]
    if args.raw_json_dir:
        json_paths = sorted(args.raw_json_dir.glob("openstack__*.json"))
    else:
        json_paths = [args.raw_json]
    logger.info(f"processing {len(json_paths)} project(s): {[p.name for p in json_paths]}")

    logger.info(f"loading reviews from {args.reviews}")
    reviews_df = pd.read_csv(args.reviews)
    logger.info(f"  {len(reviews_df):,} review rows")

    parts: List[pd.DataFrame] = []
    for jp in json_paths:
        df = process_project(jp, reviews_df, depth=args.depth)
        parts.append(df)

    full = pd.concat(parts, ignore_index=True)
    # timestamp を datetime に正規化、ソート
    # combined_raw.csv は ISO "T" 区切り、raw_json は空白 + nanosecond で
    # フォーマットが混在するため format="mixed" を指定する。
    full["timestamp"] = pd.to_datetime(full["timestamp"], errors="coerce", format="mixed")
    n_before = len(full)
    full = full.dropna(subset=["timestamp"])
    if len(full) < n_before:
        logger.warning(f"dropped {n_before - len(full)} rows with invalid timestamp")
    full = full.sort_values(["email", "timestamp"]).reset_index(drop=True)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    full.to_csv(args.output, index=False)
    logger.info(f"wrote {len(full):,} events to {args.output}")

    # サマリ
    logger.info("event_type distribution:")
    for et, c in full["event_type"].value_counts().items():
        logger.info(f"  {et}: {c:,}")
    logger.info(f"unique reviewers: {full['email'].nunique():,}")
    logger.info(f"unique changes: {full['change_id'].nunique():,}")


if __name__ == "__main__":
    main()
